### ISSUE TITLE
"focusable" is a very broad name, already kinda taken

### ISSUE THREAD

**Issue by tabatkins** [richtr/html-media-focus#2]
The concept of "focusable" is already taken by, well, focus.  Normal focus.  Adding an attribute called "focusable" that refers only to _media_ focus would be extremely confusing, and get misused everywhere by people who think it's a better way to spell `tabindex=0`.

Should use a different, more descriptive name, like `mediafocus` or something.

**Comment by richtr** [comment]
Yep. Totally agree with this. FWIW, it started off being called `queued`. Naming is clearly not my forté :)

If `vid.mediaFocus === true` then that could also be a little confusing though. I'm actually _requesting_ media focus. This name suggests I'm currently _holding_ media focus which may or may not be true. 

It's more of a request to obtain media focus than an indicator that an element currently holds media focus.

So something like `mediaFocusable` instead?

**Comment by richtr** [comment]
We could also call it `remoteControls` or `syncPlayback`.

**Comment by tabatkins** [comment]
Dunno what `syncPlayback` would mean in this context, but `remoteControls` sounds kinda good.

**Comment by richtr** [comment]
`remoteControls` it is (for now)!
